config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :full_notes
  resources :sales_contracts do
    collection do
      get :report
    end
    resources :sales_contract_realties, only: [:destroy]
    resources :sales_contract_accords, only: [:new, :create, :destroy]
  end

  resources :reason_refusal_types
  resources :document_types
  resources :scheduler_logs
  resources :revisions
  resources :prints do
    collection do
      get :delivery_notes
    end
  end
  resources :reports do
    collection do
      get :agents
      get :users_jobs
      get :users_jobs_for_user
      get :users_changes
      get :leasing_contract
      get :real_estate_agent_list
      get :created_contracts_from_agents
      get :birthday
    end
  end
  resources :revision_types
  resources :planned_prices, only: [:create]
  resources :alerts
  resources :alert_types
  resources :repaymet_types
  resources :notifications, only: [:index, :show, :deactivate_all] do
    collection do
      get :deactivate_all
    end
  end
  resources :room_messages
  resources :rooms
  resources :activities, only: [:index, :search_index] do
    collection do
      get :search_index
    end
  end
  resources :user_emails
  resources :note_leasing_contracts
  resources :terrains, only: [:create, :update]
  resources :file_boards
  resources :event_types
  resources :contracts, only: :index do
    collection do
      get :without_sales_contract
    end
  end
  resources :dispositions
  resources :month_advences
  resources :leasing_contract_realties
  resources :leasing_contract_clients
  resources :invoices
  resources :boards
  resources :user_addresses
  resources :user_mobiles
  resources :cooperations
  resources :type_of_notices
  resources :rewards
  resources :payments
  resources :leasing_contracts do
    resources :repayments do
      collection do
        get :bulk_create
        get :delete_all_repayments
      end
    end
    resources :payments
    member do
      get :uploads
      get :repayments_payments
      patch :create_uploads
      delete :delete_image
      get :reset_rent
    end
  end
  resources :permissions
  resources :addresses
  resources :distributors
  resources :energies
  resources :expert_evidences
  resources :notes
  resources :expense_types
  resources :expenses
  resources :commitment_types
  resources :expense
  resources :commitments do
    collection do
      get :full_index
    end
  end
  resources :clients
  resources :realties
  resources :realty_types
  resources :users, only: [:index,:edit,:update, :card, :new_user, :create_user]  do
    collection do
      get :changes
      get :new_user
      get :candidates
      post :create_user
    end
    member do
      get :card
      get :change_color
    end
    resources :user_documents do
      member do
        patch :uploads
      end
    end
    resources :agent_notes, only: [:new,:create, :destroy]
  end
  resources :accords do
    collection do
      get :changes
      get :automatic_list
    end
    member do
      get :uploads
      patch :refusal
      patch :create_uploads
      delete :delete_image
    end
    resources :commitments, only: [:index]
  end
  root 'home#index'
  resources :home do
    collection do
      get :balance_price_calculation
    end
  end
  resources :events do
    collection do
        post :create_html
        get :index_list
        get :all_list
    end
  end
  resources :conversations, only: [:create,:index] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
   resources :autocompleter_address do
    collection do
      get :cislo_kat_uzemi_find
      get :cislo_parcely_find
      get :obec_find
      get :ulice_find
      get :cislo_find
      get :validate_adresa
    end
  end
end

app/models/expert_evidence.rb
class ExpertEvidence < ApplicationRecord
	include RemoveWhiteSpiceFromNumberInput::MarketPlace
	has_paper_trail ignore: [:updated_at, :id]
	belongs_to :user

	scope :for_accord, -> (accord_id) {where(accord_id: accord_id)}
end

app/controllers/expert_evidences_controller.rb
class ExpertEvidencesController < ApplicationController
  before_action :set_expert_evidence, only: [:show, :edit, :update, :destroy]

  # GET /expert_evidences
  # GET /expert_evidences.json
  def index
    @expert_evidences = ExpertEvidence.all
  end

  # GET /expert_evidences/1
  # GET /expert_evidences/1.json
  def show
  end

  # GET /expert_evidences/new
  def new
    @expert_evidence = ExpertEvidence.new
  end

  # GET /expert_evidences/1/edit
  def edit
  end

  # POST /expert_evidences
  # POST /expert_evidences.json
  def create
    @expert_evidence = ExpertEvidence.new(expert_evidence_params)

    respond_to do |format|
      if @expert_evidence.save
        format.html { redirect_to @expert_evidence, notice: 'Expert evidence was successfully created.' }
        format.json { render :show, status: :created, location: @expert_evidence }
      else
        format.html { render :new }
        format.json { render json: @expert_evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expert_evidences/1
  # PATCH/PUT /expert_evidences/1.json
  def update
    respond_to do |format|
      if @expert_evidence.update(expert_evidence_params)
        format.html { redirect_to @expert_evidence, notice: 'Expert evidence was successfully updated.' }
        format.json { render :show, status: :ok, location: @expert_evidence }
      else
        format.html { render :edit }
        format.json { render json: @expert_evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expert_evidences/1
  # DELETE /expert_evidences/1.json
  def destroy
    @expert_evidence.destroy
    respond_to do |format|
      format.html { redirect_to expert_evidences_url, notice: 'Expert evidence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert_evidence
      @expert_evidence = ExpertEvidence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expert_evidence_params
      params.require(:expert_evidence).permit(:of_date, :number, :user_id, :price, :market_price, :accord_id)
    end
end

app/helpers/expert_evidences_helper.rb
module ExpertEvidencesHelper
end

app/views/expert_evidences/_form.html.erb
<%= form_with(model: expert_evidence, local: true) do |form| %>
  <% if expert_evidence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expert_evidence.errors.count, "error") %> prohibited this expert_evidence from being saved:</h2>

      <ul>
      <% expert_evidence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :of_date %>
    <%= form.date_select :of_date %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :market_price %>
    <%= form.text_field :market_price %>
  </div>

  <div class="field">
    <%= form.label :accord_id %>
    <%= form.number_field :accord_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expert_evidences/edit.html.erb
<h1>Editing Expert Evidence</h1>

<%= render 'form', expert_evidence: @expert_evidence %>

<%= link_to 'Show', @expert_evidence %> |
<%= link_to 'Back', expert_evidences_path %>

app/views/expert_evidences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expert Evidences</h1>

<table>
  <thead>
    <tr>
      <th>Of date</th>
      <th>Number</th>
      <th>User</th>
      <th>Price</th>
      <th>Market price</th>
      <th>Accord</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expert_evidences.each do |expert_evidence| %>
      <tr>
        <td><%= expert_evidence.of_date %></td>
        <td><%= expert_evidence.number %></td>
        <td><%= expert_evidence.user_id %></td>
        <td><%= expert_evidence.price %></td>
        <td><%= expert_evidence.market_price %></td>
        <td><%= expert_evidence.accord_id %></td>
        <td><%= link_to 'Show', expert_evidence %></td>
        <td><%= link_to 'Edit', edit_expert_evidence_path(expert_evidence) %></td>
        <td><%= link_to 'Destroy', expert_evidence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expert Evidence', new_expert_evidence_path %>

app/views/expert_evidences/new.html.erb
<h1>New Expert Evidence</h1>

<%= render 'form', expert_evidence: @expert_evidence %>

<%= link_to 'Back', expert_evidences_path %>

app/views/expert_evidences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Of date:</strong>
  <%= @expert_evidence.of_date %>
</p>

<p>
  <strong>Number:</strong>
  <%= @expert_evidence.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @expert_evidence.user_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @expert_evidence.price %>
</p>

<p>
  <strong>Market price:</strong>
  <%= @expert_evidence.market_price %>
</p>

<p>
  <strong>Accord:</strong>
  <%= @expert_evidence.accord_id %>
</p>

<%= link_to 'Edit', edit_expert_evidence_path(@expert_evidence) %> |
<%= link_to 'Back', expert_evidences_path %>