config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :full_notes
  resources :sales_contracts do
    collection do
      get :report
    end
    resources :sales_contract_realties, only: [:destroy]
    resources :sales_contract_accords, only: [:new, :create, :destroy]
  end

  resources :reason_refusal_types
  resources :document_types
  resources :scheduler_logs
  resources :revisions
  resources :prints do
    collection do
      get :delivery_notes
    end
  end
  resources :reports do
    collection do
      get :agents
      get :users_jobs
      get :users_jobs_for_user
      get :users_changes
      get :leasing_contract
      get :real_estate_agent_list
      get :created_contracts_from_agents
      get :birthday
    end
  end
  resources :revision_types
  resources :planned_prices, only: [:create]
  resources :alerts
  resources :alert_types
  resources :repaymet_types
  resources :notifications, only: [:index, :show, :deactivate_all] do
    collection do
      get :deactivate_all
    end
  end
  resources :room_messages
  resources :rooms
  resources :activities, only: [:index, :search_index] do
    collection do
      get :search_index
    end
  end
  resources :user_emails
  resources :note_leasing_contracts
  resources :terrains, only: [:create, :update]
  resources :file_boards
  resources :event_types
  resources :contracts, only: :index do
    collection do
      get :without_sales_contract
    end
  end
  resources :dispositions
  resources :month_advences
  resources :leasing_contract_realties
  resources :leasing_contract_clients
  resources :invoices
  resources :boards
  resources :user_addresses
  resources :user_mobiles
  resources :cooperations
  resources :type_of_notices
  resources :rewards
  resources :payments
  resources :leasing_contracts do
    resources :repayments do
      collection do
        get :bulk_create
        get :delete_all_repayments
      end
    end
    resources :payments
    member do
      get :uploads
      get :repayments_payments
      patch :create_uploads
      delete :delete_image
      get :reset_rent
    end
  end
  resources :permissions
  resources :addresses
  resources :distributors
  resources :energies
  resources :expert_evidences
  resources :notes
  resources :expense_types
  resources :expenses
  resources :commitment_types
  resources :expense
  resources :commitments do
    collection do
      get :full_index
    end
  end
  resources :clients
  resources :realties
  resources :realty_types
  resources :users, only: [:index,:edit,:update, :card, :new_user, :create_user]  do
    collection do
      get :changes
      get :new_user
      get :candidates
      post :create_user
    end
    member do
      get :card
      get :change_color
    end
    resources :user_documents do
      member do
        patch :uploads
      end
    end
    resources :agent_notes, only: [:new,:create, :destroy]
  end
  resources :accords do
    collection do
      get :changes
      get :automatic_list
    end
    member do
      get :uploads
      patch :refusal
      patch :create_uploads
      delete :delete_image
    end
    resources :commitments, only: [:index]
  end
  root 'home#index'
  resources :home do
    collection do
      get :balance_price_calculation
    end
  end
  resources :events do
    collection do
        post :create_html
        get :index_list
        get :all_list
    end
  end
  resources :conversations, only: [:create,:index] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
   resources :autocompleter_address do
    collection do
      get :cislo_kat_uzemi_find
      get :cislo_parcely_find
      get :obec_find
      get :ulice_find
      get :cislo_find
      get :validate_adresa
    end
  end
end

app/models/remove_white_spice_from_number_input/reward.rb
module RemoveWhiteSpiceFromNumberInput::Reward

	def agency_commission=(value)
		self[:agency_commission] = value.to_s.delete(" ")
	end

	def commission_for_the_contract=(value)
		self[:commission_for_the_contract] = value.to_s.delete(" ")
	end

end

app/models/reward.rb
class Reward < ApplicationRecord
	include RemoveWhiteSpiceFromNumberInput::Reward
	has_paper_trail ignore: [:updated_at]
	belongs_to :accord
	belongs_to :invoice, required: false
	belongs_to :agent, foreign_key: 'user_id', class_name: 'User'

  validate :check_agency_commission

	def create_reward(accord)
		self.accord_id= accord.id
		self.user_id = accord.agent_id
		self.agency_commission = accord.agency_commission_price
		self.commission_for_the_contract = accord.commission_for_the_contract
		self.claim_date = accord.date_of_ownership
	end

	def invoice_date
		self.invoice.try(:created_at)
	end

	def purchase_price
		accord.purchase_price
	end

  def check_agency_commission
    errors.add(:agency_commission, "Tipař nemuže mít zprostředkovatelkou provizi")  if agent.tipster? && agency_commission.to_f != 0
  end

	scope :invoice, -> (invoice_id) {where(invoice_id: invoice_id)}
	scope :for_user, -> (user_id) {where(user_id: user_id)}
	scope :without_invoice, ->  {where("invoice_id is NULL")}
	scope :subordinates_rewards, -> (user) {where(user_id: [User.where(superior_id: user.id).pluck(:id)])}

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]
  before_action :set_accord, only: [:create]

  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = policy_scope(Reward).order(claim_date: :desc).decorate
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = @reward.decorate
    respond_to do |format|
        format.html
        format.pdf {
          render pdf: "faktura"
        }
    end
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
     authorize @reward
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new
    @reward.create_reward(@accord)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @accord, notice: 'Provizní nárok byl úspěšně vytvořen.' }
        format.json { render :show, status: :created, location: @accord }
      else
        format.html { render :new }
        format.json { render json: @accord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to rewards_url, notice: 'Reward was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id]).decorate
    end

    def set_accord
      @accord = Accord.find(params[:accord_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
       params.require(:reward).permit!
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward, local: true) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :accord_id %>
    <%= form.number_field :accord_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :agency_commission %>
    <%= form.text_field :agency_commission %>
  </div>

  <div class="field">
    <%= form.label :commission_for_the_contract %>
    <%= form.text_field :commission_for_the_contract %>
  </div>

  <div class="field">
    <%= form.label :invoice_date %>
    <%= form.date_select :invoice_date %>
  </div>

  <div class="field">
    <%= form.label :payout_date %>
    <%= form.date_select :payout_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.slim
- title "Úprava provize č. " + @reward.id.to_s
div.container-fluid
	ol.breadcrumb
		li.breadcrumb-item
			b
				= link_to 'Provize', rewards_path() 
		li.breadcrumb-item
			| úprava provize č.
			= @reward.id
	div.panel-body.no-padding
        = form_with(model: @reward, local: true) do |f|
			- if @reward.errors.any?
				#error_explanation
				h2
		    		= pluralize(@reward.errors.count, "error")
		    		| prohibited this reward from being saved:
				ul
		    		- @reward.errors.full_messages.each do |message|
		      			li= message
			.card.shadow.mb-4
			    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
					h6.m-0.font-weight-bold.text-primary Data provize
				.card-body
						.form-group
							= f.label :agency_commission, "Zprostředkovatelská provize"
							= f.text_field :agency_commission, class: "form-control"
						.form-group
							= f.label :commission_for_the_contract, "Provize za smlouvu"
							= f.text_field :commission_for_the_contract, class: "form-control"
						.form-group
							= f.label :claim_date, "Datum nároku"
							= f.text_field :claim_date, class: "form-control datapicker"
						.action
				    		= f.submit "Odešli" , class: "btn btn-default", type: "submit"

app/views/rewards/index.slim
div.container-fluid
  ol.breadcrumb
    li.breadcrumb-item
      b
        | Provize
    li.breadcrumb-item
      | Přehled provizi
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
      h6.m-0.font-weight-bold.text-primary Přehled provizi
    .card-body
      p
        b 
          | Počet provizí: 
          = @rewards.size
      table.table
        tr
          th Agent
          th Nadřízený
          th Smlouva
          th Klient
          th Výkupní cena
          th Zprostředkovatelská provize
          th Provize za smlouvu
          th Datum nároku
          th Faktura
        - @rewards.each do |reward|
          tr
            td=link_to reward.agent, card_user_path(reward.user_id)
            td=reward.agent_superior
            td=link_to reward.contract, accord_path(reward.accord)
            td=reward.first_client
            td.text-right=reward.purchase_price
            td.text-right=reward.agency_commission
            td.text-right=reward.commission_for_the_contract
            td.text-right=reward.claim_date
            td= link_to "pdf", invoice_path(id: reward.invoice_id, format: :pdf) unless reward.invoice_id.blank?
            -if current_user.user_or_admin?
              td= link_to "úprava", edit_reward_path(reward)

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.pdf.slim
doctype 1.1
html xml:lang="cs" xmlns="http://www.w3.org/1999/xhtml" 
	head
    	meta content="text/html;charset=UTF-8" http-equiv="content-type" /
    	= wicked_pdf_stylesheet_link_tag "application"
  	body
		= render "show"

app/views/rewards/show.slim
= render "show"