config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :full_notes
  resources :sales_contracts do
    collection do
      get :report
    end
    resources :sales_contract_realties, only: [:destroy]
    resources :sales_contract_accords, only: [:new, :create, :destroy]
  end

  resources :reason_refusal_types
  resources :document_types
  resources :scheduler_logs
  resources :revisions
  resources :prints do
    collection do
      get :delivery_notes
    end
  end
  resources :reports do
    collection do
      get :agents
      get :users_jobs
      get :users_jobs_for_user
      get :users_changes
      get :leasing_contract
      get :real_estate_agent_list
      get :created_contracts_from_agents
      get :birthday
    end
  end
  resources :revision_types
  resources :planned_prices, only: [:create]
  resources :alerts
  resources :alert_types
  resources :repaymet_types
  resources :notifications, only: [:index, :show, :deactivate_all] do
    collection do
      get :deactivate_all
    end
  end
  resources :room_messages
  resources :rooms
  resources :activities, only: [:index, :search_index] do
    collection do
      get :search_index
    end
  end
  resources :user_emails
  resources :note_leasing_contracts
  resources :terrains, only: [:create, :update]
  resources :file_boards
  resources :event_types
  resources :contracts, only: :index do
    collection do
      get :without_sales_contract
    end
  end
  resources :dispositions
  resources :month_advences
  resources :leasing_contract_realties
  resources :leasing_contract_clients
  resources :invoices
  resources :boards
  resources :user_addresses
  resources :user_mobiles
  resources :cooperations
  resources :type_of_notices
  resources :rewards
  resources :payments
  resources :leasing_contracts do
    resources :repayments do
      collection do
        get :bulk_create
        get :delete_all_repayments
      end
    end
    resources :payments
    member do
      get :uploads
      get :repayments_payments
      patch :create_uploads
      delete :delete_image
      get :reset_rent
    end
  end
  resources :permissions
  resources :addresses
  resources :distributors
  resources :energies
  resources :expert_evidences
  resources :notes
  resources :expense_types
  resources :expenses
  resources :commitment_types
  resources :expense
  resources :commitments do
    collection do
      get :full_index
    end
  end
  resources :clients
  resources :realties
  resources :realty_types
  resources :users, only: [:index,:edit,:update, :card, :new_user, :create_user]  do
    collection do
      get :changes
      get :new_user
      get :candidates
      post :create_user
    end
    member do
      get :card
      get :change_color
    end
    resources :user_documents do
      member do
        patch :uploads
      end
    end
    resources :agent_notes, only: [:new,:create, :destroy]
  end
  resources :accords do
    collection do
      get :changes
      get :automatic_list
    end
    member do
      get :uploads
      patch :refusal
      patch :create_uploads
      delete :delete_image
    end
    resources :commitments, only: [:index]
  end
  root 'home#index'
  resources :home do
    collection do
      get :balance_price_calculation
    end
  end
  resources :events do
    collection do
        post :create_html
        get :index_list
        get :all_list
    end
  end
  resources :conversations, only: [:create,:index] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
   resources :autocompleter_address do
    collection do
      get :cislo_kat_uzemi_find
      get :cislo_parcely_find
      get :obec_find
      get :ulice_find
      get :cislo_find
      get :validate_adresa
    end
  end
end

app/controllers/realty_types_controller.rb
class RealtyTypesController < ApplicationController
  before_action :set_realty_type, only: [:show, :edit, :update, :destroy]

  # GET /realty_types
  # GET /realty_types.json
  def index
    @realty_types = RealtyType.all
  end

  # GET /realty_types/1
  # GET /realty_types/1.json
  def show
  end

  # GET /realty_types/new
  def new
    @realty_type = RealtyType.new
  end

  # GET /realty_types/1/edit
  def edit
  end

  # POST /realty_types
  # POST /realty_types.json
  def create
    @realty_type = RealtyType.new(realty_type_params)

    respond_to do |format|
      if @realty_type.save
        format.html { redirect_to @realty_type, notice: 'Realty type was successfully created.' }
        format.json { render :show, status: :created, location: @realty_type }
      else
        format.html { render :new }
        format.json { render json: @realty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /realty_types/1
  # PATCH/PUT /realty_types/1.json
  def update
    respond_to do |format|
      if @realty_type.update(realty_type_params)
        format.html { redirect_to @realty_type, notice: 'Realty type was successfully updated.' }
        format.json { render :show, status: :ok, location: @realty_type }
      else
        format.html { render :edit }
        format.json { render json: @realty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /realty_types/1
  # DELETE /realty_types/1.json
  def destroy
    @realty_type.destroy
    respond_to do |format|
      format.html { redirect_to realty_types_url, notice: 'Realty type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realty_type
      @realty_type = RealtyType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realty_type_params
      params.require(:realty_type).permit(:name)
    end
end

app/helpers/realty_types_helper.rb
module RealtyTypesHelper
end

app/views/realty_types/_form.html.erb
<%= form_with(model: realty_type, local: true) do |form| %>
  <% if realty_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(realty_type.errors.count, "error") %> prohibited this realty_type from being saved:</h2>

      <ul>
      <% realty_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/realty_types/edit.html.erb
<h1>Editing Realty Type</h1>

<%= render 'form', realty_type: @realty_type %>

<%= link_to 'Show', @realty_type %> |
<%= link_to 'Back', realty_types_path %>

app/views/realty_types/index.slim
div.container-fluid
  ol.breadcrumb
    li.breadcrumb-item
      b
        | 
    li.breadcrumb-item
      | Přehled typů nemovitostí
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
      h6.m-0.font-weight-bold.text-primary Přehled typů nemovitostí
      div.col-md-2.nopadding.text-right.panel-title
        = link_to 'Nový typ nemovitosti', new_realty_type_path
    .card-body
      table.table
        thead
          tr
            th Jméno
        tbody
          - @realty_types.each do |realty_type|
            tr
              td= link_to realty_type.name, edit_realty_type_path(realty_type)

app/views/realty_types/new.html.erb
<h1>New Realty Type</h1>

<%= render 'form', realty_type: @realty_type %>

<%= link_to 'Back', realty_types_path %>

app/views/realty_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @realty_type.name %>
</p>

<%= link_to 'Edit', edit_realty_type_path(@realty_type) %> |
<%= link_to 'Back', realty_types_path %>