config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :full_notes
  resources :sales_contracts do
    collection do
      get :report
    end
    resources :sales_contract_realties, only: [:destroy]
    resources :sales_contract_accords, only: [:new, :create, :destroy]
  end

  resources :reason_refusal_types
  resources :document_types
  resources :scheduler_logs
  resources :revisions
  resources :prints do
    collection do
      get :delivery_notes
    end
  end
  resources :reports do
    collection do
      get :agents
      get :users_jobs
      get :users_jobs_for_user
      get :users_changes
      get :leasing_contract
      get :real_estate_agent_list
      get :created_contracts_from_agents
      get :birthday
    end
  end
  resources :revision_types
  resources :planned_prices, only: [:create]
  resources :alerts
  resources :alert_types
  resources :repaymet_types
  resources :notifications, only: [:index, :show, :deactivate_all] do
    collection do
      get :deactivate_all
    end
  end
  resources :room_messages
  resources :rooms
  resources :activities, only: [:index, :search_index] do
    collection do
      get :search_index
    end
  end
  resources :user_emails
  resources :note_leasing_contracts
  resources :terrains, only: [:create, :update]
  resources :file_boards
  resources :event_types
  resources :contracts, only: :index do
    collection do
      get :without_sales_contract
    end
  end
  resources :dispositions
  resources :month_advences
  resources :leasing_contract_realties
  resources :leasing_contract_clients
  resources :invoices
  resources :boards
  resources :user_addresses
  resources :user_mobiles
  resources :cooperations
  resources :type_of_notices
  resources :rewards
  resources :payments
  resources :leasing_contracts do
    resources :repayments do
      collection do
        get :bulk_create
        get :delete_all_repayments
      end
    end
    resources :payments
    member do
      get :uploads
      get :repayments_payments
      patch :create_uploads
      delete :delete_image
      get :reset_rent
    end
  end
  resources :permissions
  resources :addresses
  resources :distributors
  resources :energies
  resources :expert_evidences
  resources :notes
  resources :expense_types
  resources :expenses
  resources :commitment_types
  resources :expense
  resources :commitments do
    collection do
      get :full_index
    end
  end
  resources :clients
  resources :realties
  resources :realty_types
  resources :users, only: [:index,:edit,:update, :card, :new_user, :create_user]  do
    collection do
      get :changes
      get :new_user
      get :candidates
      post :create_user
    end
    member do
      get :card
      get :change_color
    end
    resources :user_documents do
      member do
        patch :uploads
      end
    end
    resources :agent_notes, only: [:new,:create, :destroy]
  end
  resources :accords do
    collection do
      get :changes
      get :automatic_list
    end
    member do
      get :uploads
      patch :refusal
      patch :create_uploads
      delete :delete_image
    end
    resources :commitments, only: [:index]
  end
  root 'home#index'
  resources :home do
    collection do
      get :balance_price_calculation
    end
  end
  resources :events do
    collection do
        post :create_html
        get :index_list
        get :all_list
    end
  end
  resources :conversations, only: [:create,:index] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
      }
   resources :autocompleter_address do
    collection do
      get :cislo_kat_uzemi_find
      get :cislo_parcely_find
      get :obec_find
      get :ulice_find
      get :cislo_find
      get :validate_adresa
    end
  end
end

app/models/report.rb
class Report

	def self.colums(user)
		Report::colums_for_user_perrmision(user).map{|a,b| [b,a]}
	end

	def self.colums_for_user_perrmision(user)
		if user.admin?
			User.filtering_attributes_manager.merge(User.filtering_attributes_admin)
		elsif user.manager? || user.user?
			User.filtering_attributes_manager
		else
			User.filtering_attributes_agent
		end
	end

  def self.users_job_actity(user, date_from, date_to)
    Reports::UserAccord::users_job_actity(user, date_from, date_to)
  end
end

app/models/reports/leasing_contracts.rb
module Reports::LeasingContracts
  include ActionView::Helpers::NumberHelper
  def accords_by_month
    Accord.where(state: 'contract').select("accords.created_at, month(date_of_signature) as month, year(date_of_signature) as year").group(:month,:year).map{|a| [Date.new(a.year, a.month,1)]}.sort_by(&:first)
  end

  def accords_by_year
    Accord.where(state: 'contract').select("accords.created_at, year(date_of_signature) as year").group(:year).map{|a| [Date.new(a.year, 1,1)]}.sort_by(&:first)
  end

  def sum_purchace_price_for_period(from, to)
    number_to_currency(Accord.where(state: 'contract').where.not(id: sales_contract_from_period(to)).where("date_of_signature < ?", to).sum(:purchase_price), unit: "Kč", separator: ",", delimiter: " ", format: "%n %u",  precision: 0)
  end

  def count_purchace_price_for_period(from, to)
    Accord.where(state: 'contract').where.not(id: sales_contract_from_period(to)).where("date_of_signature < ?", to).count
  end

  def count_leasing_contract_from_period(from, to )
    LeasingContract.where.not(accord_id: sales_contract_from_period(to)).where("rent_from < ? AND rent_to > ?",to, to).count
  end

  def sum_purchace_price_leasing_contract_from_period(from, to)
    number_to_currency(LeasingContract.where.not(accord_id: sales_contract_from_period(to)).where("rent_from < ? AND rent_to > ? ",to, to).joins(:accord).sum(:purchase_price), unit: "Kč", separator: ",", delimiter: " ", format: "%n %u",  precision: 0)
  end

  def sum_monthly_rent_leasing_contract_from_period(from, to)
    number_to_currency(LeasingContract.where.not(accord_id: sales_contract_from_period(to)).where("rent_from < ? AND rent_to > ?",to, to).sum(:monthly_rent), unit: "Kč", separator: ",", delimiter: " ", format: "%n %u",  precision: 0)
  end 

  def sum_payments_rent_leasing_contract_from_period(from, to)
    number_to_currency(Payment.where("payment_date < ? AND payment_date >= ?", to, from).sum(:amount), unit: "Kč", separator: ",", delimiter: " ", format: "%n %u",  precision: 0)
  end

  def sales_contract_from_period(to)
    SalesContract.where("date_of_sale_realty < ?", to).pluck(:accord_id)
  end

end

app/models/reports/user.rb
module Reports::User

	def agent_contracts_bussines
		accord_for_user_in_interval.state("contract")
	end

	def accord_for_user_in_interval
		Accord.agent_id(User.subordinates(self).pluck(:id) << id)
	end

	def accord_for_user_in_interval_in_signature
		Accord.agent_signature(User.subordinates(self).pluck(:id) << id)
	end

	def contract_volume_bussines
		agent_contracts_bussines.sum(:purchase_price)
	end

	def count_contract_bussines
		agent_contracts_bussines.count
	end

	def sum_contract_one_of_payment
		agent_contracts_bussines.joins(:commitments).where('commitments.commitment_type_id': [4,5,6]).sum(:amount)
	end

	def events_for_the_period
		Event.for_user(id).count
	end

	def events_meeting_with_advisors
		Event.for_user(id).where(title: ['Servisní návštěva', 'Akviziční schůzka']).count
	end

	def count_accord_for_user_in_interval
		Accord.agent_id(User.subordinates(self).pluck(:id) << id).count
	end

	def count_accord_to_terrain
		accord_for_user_in_interval.agent_in_terrain([User.subordinates(self).pluck(:id) << id]).count
	end

	def count_new_cooperation
		User.subordinates(self).count
	end

	def count_not_termination_cooperation
		User.can_sign_in.subordinates(self).select(&:not_runing_notice?).size
	end

	def count_active_cooperation
		User.can_sign_in.subordinates(self).select(&:date_of_last_create_accord_smaller_then_60?).size
	end

	def count_not_termination_incomplate_cooperation
		User.can_sign_in.subordinates(self).select(&:not_runing_notice?).select(&:complate_documentation?).size
	end

	def contract_volume_servise
		accord_for_user_in_interval_in_signature.sum(:purchase_price)
	end

	def count_contract_servise
		accord_for_user_in_interval_in_signature.count
	end

	def sum_contract_one_of_payment_service
		accord_for_user_in_interval_in_signature.joins(:commitments).where('commitments.commitment_type_id': [4,5,6]).sum(:amount)
	end

	def count_active_state
		Accord.where(agent_id: accord_for_user_in_interval.pluck(:id)).select(&:active_state_between_date?)
	end
end

app/models/reports/user_accord.rb
module Reports::UserAccord
  def self.users_job_actity(user, date_from, date_to)
    return if user.blank?
    return if date_from.blank?
    return if date_to.blank?

    created_accords = Accord.created_by(user.id).start_created_at(date_from).end_created_at(date_to).pluck(:id)
    eborated_accords = eborated_accords_find(user, date_from, date_to)
    refuse_or_dowload_accords = refuse_or_dowload_accords_find(user, date_from, date_to)
    in_terain_accords = in_terrain_accords_find(user, date_from, date_to)
    to_sign_accords = to_sign_accords_accords_find(user, date_from, date_to)
    {created_accords: created_accords, eborated_accord: eborated_accords, refuse_or_dowload_accords: refuse_or_dowload_accords, in_terain_accords: in_terain_accords, to_sign_accords: to_sign_accords}
  end

  def self.eborated_accords_find(user, date_from, date_to)
    date_to = date_to.to_date.end_of_day
    versions = Version.where(whodunnit: user).where(item_type: "Accord").where(event: "update").where(created_at: date_from..date_to)
    attribut_changes(versions, 'state').select{|user_id, states, time, id|  states.last == 2}.map{|a| a.last}.uniq.select{|a| Accord.exists?(a)}
  end


  def self.refuse_or_dowload_accords_find(user, date_from, date_to)
    date_to = date_to.to_date.end_of_day
    versions = Version.where(whodunnit: user).where(item_type: "Accord").where(event: "update").where(created_at: date_from..date_to)
    attribut_changes(versions, 'state').select{|user_id, states, time, id|  states.last == 5 || states.last == 6}.map{|a| a.last}.uniq.select{|a| Accord.exists?(a)}
  end

  def self.in_terrain_accords_find(user, date_from, date_to)
    date_to = date_to.to_date.end_of_day
    versions = Version.where(whodunnit: user).where(item_type: "Accord").where(event: "update").where("created_at >= ?", date_from).where("created_at <= ?", date_to)
    attribut_changes(versions, 'state').select{|user_id, states, time, id|  states.last == 2}.map{|a| a.last}.uniq.select{|a| Accord.exists?(a)}
  end

  def self.to_sign_accords_accords_find(user, date_from, date_to)
    date_to = date_to.to_date.end_of_day
    versions = Version.where(whodunnit: user).where(item_type: "Accord").where(event: "update").where(created_at: date_from..date_to)
    attribut_changes(versions, 'state').select{|user_id, states, time, id|  states.last == 3}.map{|a| a.last}.uniq.select{|a| Accord.exists?(a)}
  end

  def self.attribut_changes(versions, attribute)
    versions.select{|a| a.object_changes && a.object_changes.include?(attribute)}.map{|a| [a.whodunnit, PaperTrail.serializer.load(a.object_changes)[attribute], a.created_at, a.item_id]}
  end
end

#attribut_changes("state").select{|user_id, states, time|  user_id == user.id && states.last == 'state_eleboration'}
#Version.where(whodunnit: User.first).where(item_type: "Accord").where(event: "update").where(created_at: date_from..date_to)

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'simple', only: :real_estate_agent_list

	def agents
		request.format = 'csv' if params[:commit] == 'CSV'
		@colums = Report::colums(current_user)
		@users = policy_scope(User)
		@filter_users = @users
		@company = @filter_users.map{|a| [a.name_company,a.name_company]}.uniq
		@users =  IndexFilter::IndexServices.new(@users,params.dup).perform
		respond_to do |format|
			format.html{ @users = @users.decorate}
			format.csv{ send_data @users.to_csv(params[:colums]), filename: "users-#{Date.today}.csv" }
		end
	end

	def users_jobs
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" unless current_user.admin?
		@users = User.admin_and_user
	  Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled práce uživatelů", objet: "report_users_jobs")
  end


  def users_jobs_for_user
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" unless current_user.admin?
    @user = User.find_by_id (params[:user_id])
    @report = Report::users_job_actity(@user, params[:date_from],params[:date_to])
    Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled práce uživatelů za uživatele", objet: "report_users_jobs_for_user")
  end

  def users_changes
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" unless current_user.admin?
    @versions = PaperTrail::Version.where(item_type: "User").where(event: "update").order(created_at: :desc)
    @versions = @versions + PaperTrail::Version.where(item_type: "Address").where(item_id: Address.joins(:user_address).pluck("address_id")).where(event: "update").where(whodunnit: User.manager_and_agents_and_tipster.pluck(:id))
    @versions = @versions + PaperTrail::Version.where(item_type: "Mobile").where(item_id: Mobile.joins(:user_mobiles).pluck("mobile_id")).where(event: "update").where(whodunnit: User.manager_and_agents_and_tipster.pluck(:id))
    @versions = @versions + PaperTrail::Version.where(item_type: "Email").where(item_id: Email.joins(:user_emails).pluck("email_id")).where(event: "update").where(whodunnit: User.manager_and_agents_and_tipster.pluck(:id))
    @versions = @versions.sort_by(&:created_at).reverse
    Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled změn agentů od agentů", objet: "report_users_changes")
  end

  def leasing_contract
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" unless current_user.admin?
    Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled nájmeních smluv za období", objet: "report_leasing_contract")
  end

  def real_estate_agent_list
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" unless current_user.admin?
    @users = User.agents.includes(:ares).includes(:permission).includes(:email).order(can_sign_in: :desc).decorate
    Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled agentů s živnostní realitní zprostředkování", objet: "real_estate_agent_list")
  end

  def created_contracts_from_agents
     return redirect_to root_path, alert: "Nemáte potřebná oprávnění" if !current_user.user? && !current_user.admin?
     @users = User.agents.includes(:agent_accords, :permission).order(can_sign_in: :desc).decorate
     Activity.create(true_user_id: user_masquerade_owner.try(:id),user_id: current_user.id, what: "Přehled agentů počet navedených smluv a žádostí", objet: "created_contracts_from_agents")
  end

  def birthday
    return redirect_to root_path, alert: "Nemáte potřebná oprávnění" if !current_user.admin?
    @users = User.can_sign_in.manager_and_agents_and_tipster.order("extract(month from birthdate) ASC").order("extract(month from birthdate) ASC").decorate
  end
end

app/views/reports/_agents_filter.slim
= form_tag(agents_reports_path(), {method: :get}) do 
	.col-xl-3.col-lg-3
	  .card.shadow.mb-4
	    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
	      h6.m-0.font-weight-bold.text-primary Sloupce
	    .card-body
	    	.form-group
				= label_tag :columns, "Sloupce"
				= select_tag :colums, options_for_select(@colums, params[:colums]), {class: "form-control input-sm",data: {"live-search": true}, multiple: true }
	.col-xl-9.col-lg-9
	  .card.shadow.mb-4
	    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
	      h6.m-0.font-weight-bold.text-primary Filter
	    .card-body
	    	.row.p-3
				.col-xl-2
					.input-group
						= label_tag :between_count_accords, "Celkem žádostí"
						br
						= text_field_tag "between_count_accords[]",first_or_nil(params[:between_count_accords]), class: "form-control input-sm col-xl-6"
						= text_field_tag "between_count_accords[]",last_or_nil(params[:between_count_accords]), class: "form-control input-sm col-xl-6"
					.input-group
						= label_tag :between_count_accords, "Datum navedení poslední žádosti"
						br
						= text_field_tag "between_date_of_last_accord[]",first_or_nil(params[:between_date_of_last_accord]), class: "form-control input-sm col-xl-6"
						= text_field_tag "between_date_of_last_accord[]",last_or_nil(params[:between_date_of_last_accord]), class: "form-control input-sm col-xl-6"
					.input-group
						= label_tag :between_received_terrain, "Datum obdrženo do terénu"
						br
						= text_field_tag "between_received_terrain[]",first_or_nil(params[:between_received_terrain]), class: "form-control input-sm col-xl-6"
						= text_field_tag "between_received_terrain[]",last_or_nil(params[:between_received_terrain]), class: "form-control input-sm col-xl-6"
					.input-group
						= label_tag :between_date_ol_last_terrain, "Datum obdrženo do terénu"
						br
						= text_field_tag "between_date_ol_last_terrain[]",first_or_nil(params[:between_date_ol_last_terrain]), class: "form-control input-sm col-xl-6"
						= text_field_tag "between_date_ol_last_terrain[]",last_or_nil(params[:between_date_ol_last_terrain]), class: "form-control input-sm col-xl-6"
			.row.p-3
				.col-xl-2
					.form-group
						= label_tag :subordinates_id, "Nadřízený"
						= select_tag :subordinates_id, options_for_select(User.where("id != 1").pluck(:superior_id).uniq.map{|a| [User.find_by_id(a).try(:all_name),a]}, params[:subordinates_id]), {include_blank: true, class: "form-control input-sm",data: {"live-search": true}, multiple: true }
					.form-group
						= label_tag :username, 'Username'
						= text_field_tag :username,  params[:username], class: "form-control input-sm"
				.col-xl-2
					.form-group
						= label_tag :permission_fo_user, "Role"
						= select_tag :permission_fo_user, options_for_select(Permission.kinds.keys.map{|a| [a,a]}, params[:permission_fo_user]), {include_blank: true, class: "form-control input-sm",data: {"live-search": true}, multiple: true }
					.form-group
						= label_tag :id_user, "User"
						= select_tag :id_user, options_for_select(@filter_users.map{|a| [a.all_name,a.id]}, params[:id_user]), {include_blank: true, class: "form-control input-sm",data: {"live-search": true}, multiple: true }
					.form-group
						= label_tag :company, "Společnost Agenta"
						= select_tag :company, options_for_select(@company, params[:company]), {include_blank: true, class: "form-control input-sm",data: {"live-search": true}, multiple: true }
	    	.form-group.float-right
				= submit_tag "Vyhledat"
				br
				= submit_tag "CSV"

javascript: 
	$(document).ready(function () {
	    $("ul").sortable({
	        revert: true,
	        /*update: function (event, ui) {
	            // Some code to prevent duplicates
	        }*/
	    });
	    $(".draggable").draggable({
	        connectToSortable: '.sortableList',
	        cursor: 'pointer',
	        helper: 'clone',
	        revert: 'invalid'
	    });
	});

app/views/reports/agents.slim
= render 'agents_filter'
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    .card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
      h6.m-0.font-weight-bold.text-primary Přehled Pro Agenty
    .card-body
    	- unless params[:colums].blank?
    		p
		        b
		          | Počet vyhledaných agentů:
		          = @users.size
	    	table.table.table-striped style="overflow: auto; display:inline-block"
	    		tr
		    		- params[:colums].each do |colum|
		    			th = User::filtering_attributes[colum]
		    		- @users.each do |user|
		    			tr
		    				- params[:colums].each do |colum|
		    					td = user.send(colum)

app/views/reports/birthday.slim
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    h6.m-0.font-weight-bold.text-primary class="d-block card-header py-3"
      | Přehled narozenin uživatelů
    .card-body
      table.table style="overflow: auto; display:inline-block"
        tr.text-dark
          th Oprávnění
          th
          th Agent
          th OM
          th Narozeniny
        - @users.each do |user|
          tr
            td =user.permission_to_s
            td
              - if user.can_login?
                  i class="fa fa-unlock" style="color:green"
              - else
                  i class="fa fa-lock " style="color:red"
            td = user.all_name
            td = user.superior
            td = user.birthdate

app/views/reports/created_contracts_from_agents.slim
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    h6.m-0.font-weight-bold.text-primary class="d-block card-header py-3"
      | Počet naveneých smluv a žádostí od roku 1.4.2020
    .card-body
      table.table style="overflow: auto; display:inline-block"
        tr.text-dark
          th Oprávnění
          th
          th Agent
          th OM
          th Jméno společnosti
          th Datum narození
          th Datum navázání spolupráce
          th Datum navedení poslední žádosti
          th Navedených žádostí od 1.1.2020
          th Navedených smluv od 1.1.2020
        - @users.each do |user|
          tr
            td =user.permission_to_s
            td
              - if user.can_login?
                  i class="fa fa-unlock" style="color:green"
              - else
                  i class="fa fa-lock " style="color:red"
            td = user.all_name
            td = user.superior
            td = user.name_company
            td = user.birthdate
            td = user.date_of_cooperation
            td = user.date_of_last_create_accord
            td = user.agent_accords.where("accords.created_at >= ?", "1.4.2020".to_date).count
            td = user.agent_accords.where("accords.date_of_signature >= ?", "1.4.2020".to_date).state('contract').count

app/views/reports/real_estate_agent_list.slim
.col-xl-12.col-lg-12
  .card.shadow.mb-4
    h6.m-0.font-weight-bold.text-primary class="d-block card-header py-3"
      | Přehled agentů s živnostní realitní zprostředkování
    .card-body
      table.table style="overflow: auto; display:inline-block"
        tr.text-dark
          th Oprávnění
          th
          th Agent
          th OM
          th Má živnost
        - @users.each do |user|
          tr
            td =user.permission_to_s
            td
              - if user.can_login?
                  i class="fa fa-unlock" style="color:green"
              - else
                  i class="fa fa-lock " style="color:red"
            td = user.all_name
            td =user.superior
            td = check(user.ares.pluck(:nace_name).include?("Realitní zprostředkování"))

app/views/reports/users_jobs_for_user.slim
- title "Výkaz uživatele "
div.container-fluid
	ol.breadcrumb
    	li.breadcrumb-item
			b
				| Výkaz 
    	li.breadcrumb-item
			| uživatele
.col-xl-12.col-lg-12
	.card.shadow.mb-4
		.card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
			h6.m-0.font-weight-bold.text-primary Filter 
    	.card-body
    		= form_tag(users_jobs_for_user_reports_path(), {method: :get}) do
	    		.form-group
					= label_tag :user_id, "V péči"
					= select_tag :user_id, options_for_select(User.admin_and_user.uniq.map{|a| [User.find_by_id(a).try(:all_name),a.id]}, params[:user_id]), {include_blank: true, class: "form-control input-sm",data: {"live-search": true} }
				.form-group
					= label_tag :date_from, "Datum od"
					= text_field_tag :date_from, params[:date_from], class: "datapicker form-control input-sm"
				.form-group
					= label_tag :date_to, "Datum do"
					= text_field_tag :date_to, params[:date_to], class: "datapicker form-control input-sm"
				.form-group
					= submit_tag "Vyhledat"
- unless @report.blank?
	.col-xl-12.col-lg-12
		.card.shadow.mb-4
			.card-header.py-3.d-flex.flex-row.align-items-center.justify-content-between
	      		h6.m-0.font-weight-bold.text-primary Výkaz aktivity
	      		div.col-md-2.nopadding.text-right.panel-title
	    	.card-body
	    		card.shadow.mb-4
					.a href="#colapseCreatedAccord" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="colapseCreatedAccord"
	      				h6.m-0.font-weight-bold.text-dark
	      					| Vytvořeno žádostí: #{@report[:created_accords].size}
	  			    .collapse id="colapseCreatedAccord"
	    				.card-body
	    					- @report[:created_accords].each do |accord_id|
	    						= link_to accord_id, accord_path(accord_id)
	    						|  
	    		card.shadow.mb-4
					.a href="#colapseelEboratedAccord" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="colapseelEboratedAccord"
	      				h6.m-0.font-weight-bold.text-dark
	      					| Rozpracováno žádostí: #{@report[:eborated_accord].size}
	  			    .collapse id="colapseelEboratedAccord"
	    				.card-body
	    					- @report[:eborated_accord].each do |accord_id|
	    						= link_to accord_id, accord_path(accord_id)
	    						|  
	    		card.shadow.mb-4
					.a href="#colapseelrefuse_or_dowload_accords" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="colapseelrefuse_or_dowload_accords"
	      				h6.m-0.font-weight-bold.text-dark
	      					| Zamítnuto/Stáhnuto žádostí: #{@report[:refuse_or_dowload_accords].size}
	  			    .collapse id="colapseelrefuse_or_dowload_accords"
	    				.card-body
	    					- @report[:refuse_or_dowload_accords].each do |accord_id|
	    						= link_to accord_id, accord_path(accord_id)
	    						|  
	    		card.shadow.mb-4
					.a href="#colapsein_terrain" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="colapsein_terrain"
	      				h6.m-0.font-weight-bold.text-dark
	      					| V terénu žádostí: #{@report[:in_terain_accords].size}
	  			    .collapse id="colapsein_terrain"
	    				.card-body
	    					- @report[:in_terain_accords].each do |accord_id|
	    						= link_to accord_id, accord_path(accord_id)
	    						|  
	    		card.shadow.mb-4
					.a href="#colapseto_sign_accords" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="colapseto_sign_accords"
	      				h6.m-0.font-weight-bold.text-dark
	      					| Přeáno ke schválení žádostí: #{@report[:to_sign_accords].size}
	  			    .collapse id="colapseto_sign_accords"
	    				.card-body
	    					- @report[:to_sign_accords].each do |accord_id|
	    						= link_to accord_id, accord_path(accord_id)
	    						|  